#!/Usr/bin/env bash

rm -rf /tmp/cljdoc
mkdir -p /tmp/cljdoc
version=$(grep '<version>' pom.xml | head -1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')

echo "---- cljdoc preview: installing jar in local repo"
clj -A:jar & clj -A:install

echo "---- cljdoc preview: ingesting clj-salt-api"
docker run --rm -v "$PWD:/clj-salt-api" \
       -v "$HOME/.m2:/root/.m2" -v /tmp/cljdoc:/app/data --entrypoint "clojure" \
       cljdoc/cljdoc -A:cli ingest -p clj-salt-api/clj-salt-api -v "$version" \
       --jar /root/.m2/repository/clj-salt-api/clj-salt-api/"$version"/clj-salt-api-"$version".jar \
       --pom /root/.m2/repository/clj-salt-api/clj-salt-api/"$version"/clj-salt-api-"$version".pom \
       --git /clj-salt-api \
       --rev "master"

echo "---- cljdoc preview: starting server on port 8000"
docker run --rm -p 8000:8000 -v /tmp/cljdoc:/app/data cljdoc/cljdoc
