version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Lint with clj-kondo
          command: clojure -A:kondo
      - run:
          name: Run tests
          command: bin/kaocha --profile :ci
      - run:
          name: Build jar
          command: clojure -A:jar
      - store_artifacts:
          path: target/clj-salt-api.jar
          destination: clj-salt-api.jar
      - store_test_results:
          path: target/test-results
      - codecov/upload:
          file: target/coverage/codecov.json
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
    
