#!/usr/bin/env bash

rm -rf /tmp/cljdoc
mkdir -p /tmp/cljdoc
version=$(grep '<version>' pom.xml | head -1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')

echo "---- cljdoc preview: installing jar in local repo"
clj -A:jar & clj -A:install

echo "---- cljdoc preview: ingesting clj-salt-api"
docker run --rm -v "$PWD:/clj-kondo" \
       -v "$HOME/.m2:/root/.m2" -v /tmp/cljdoc:/app/data --entrypoint "clojure" \
       cljdoc/cljdoc -A:cli ingest -p clj-salt-api/clj-salt-api -v "$version" \
       --git /clj-salt-api

echo "---- cljdoc preview: starting server on port 8000"
docker run --rm -p 8000:8000 -v /tmp/cljdoc:/app/data cljdoc/cljdoc
